2023-10-02 18:55:06,118 ERROR frappe Failed to run after request hook
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 122, in application
    response = handle_exception(e)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 384, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/utils.py", line 515, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 170, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 136, in application
    run_after_request_hooks(request, response)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 151, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:06,120 ERROR frappe Could not take error snapshot: '[' was never closed (hooks.py, line 94)
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 84, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/document.py", line 78, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:06,182 ERROR frappe Failed to run after request hook
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 122, in application
    response = handle_exception(e)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 384, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/utils.py", line 515, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 170, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 136, in application
    run_after_request_hooks(request, response)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 151, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:12,754 ERROR frappe Could not take error snapshot: '[' was never closed (hooks.py, line 94)
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 84, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/document.py", line 78, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:12,761 ERROR frappe Failed to run after request hook
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 122, in application
    response = handle_exception(e)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 384, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/utils.py", line 515, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 170, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 136, in application
    run_after_request_hooks(request, response)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 151, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:13,153 ERROR frappe Could not take error snapshot: '[' was never closed (hooks.py, line 94)
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 84, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/document.py", line 78, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:13,162 ERROR frappe Failed to run after request hook
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 122, in application
    response = handle_exception(e)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 384, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/utils.py", line 515, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 170, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 136, in application
    run_after_request_hooks(request, response)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 151, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:13,510 ERROR frappe Could not take error snapshot: '[' was never closed (hooks.py, line 94)
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 84, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/document.py", line 78, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:13,516 ERROR frappe Failed to run after request hook
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 122, in application
    response = handle_exception(e)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 384, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/utils.py", line 515, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 170, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 136, in application
    run_after_request_hooks(request, response)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 151, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:13,785 ERROR frappe Could not take error snapshot: '[' was never closed (hooks.py, line 94)
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 84, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/document.py", line 78, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:13,796 ERROR frappe Failed to run after request hook
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 122, in application
    response = handle_exception(e)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 384, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/utils.py", line 515, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 170, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 136, in application
    run_after_request_hooks(request, response)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 151, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
2023-10-02 18:55:14,285 ERROR frappe Could not take error snapshot: '[' was never closed (hooks.py, line 94)
Site: ride.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 93, in application
    init_request(request)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/app.py", line 184, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 84, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/document.py", line 78, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/mohan360ithub/frappe-course/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mohan360ithub/frappe-course/apps/restaurants/restaurants/hooks.py", line 94
    standard_portal_menu_items = [
                                 ^
SyntaxError: '[' was never closed
